docs/gitrepo-add.md
This is not the documentation for helm charts, they use `helmSecretName`, instead.
This closes https://github.com/rancher/fleet/issues/765 and https://github.com/rancher/fleet/issues/238
=> Add http basic auth instructions for repos

docs/multi-tenancy.md, docs/namespaces.md, sidebars.js
The `AllowedTargetNamespaces` feature is not yet available in any released version of fleet.
=> AllowedTargetNamespaces GitRepoRestriction

docs/gitrepo-structure.md
@manno found a small mistake in the docs I introduced with #17
=> docs: fix incorrect template string

docs/gitrepo-structure.md
This adds the missing bundleSelector field and shows how you can configure labels in a bundle.
The feature was added in https://github.com/rancher/fleet/pull/552. There was a docs PR https://github.com/rancher/fleet/pull/574, but this was never merged.
=> Update dependsOn docs

docs/gitrepo-add.md, versioned_docs/version-0.4/gitrepo-add.md, versioned_docs/version-0.5/gitrepo-add.md
`pollingInterval` is a duration, so it expects a string with a unit of measure rather than an integer.
I also took the liberty to add a performance-related note.
All of this came up investigating the following case: https://jira.suse.com/browse/SURE-3613?focusedCommentId=1246937&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1246937
Supersedes #49
=> Fix pollingInterval description

docs/namespaces.md, docs/troubleshooting.md, versioned_docs/version-0.5/gitrepo-add.md, versioned_docs/version-0.5/namespaces.md, versioned_docs/version-0.5/troubleshooting.md, versioned_docs/version-0.6/namespaces.md, versioned_docs/version-0.6/troubleshooting.md
Cluster migration is more difficult
Refers to https://github.com/rancher/fleet/issues/1489
=> Remove instructions to move clusters

docs/bundle-diffs.md
This change fixes a URL that now 404s after repo structure changes. This fixes the 404 caused by https://github.com/rancher/fleet-examples/pull/39
=> Update bundle-diffs.md for broken URL

docs/gitrepo-add.md, docs/namespaces.md, versioned_docs/version-0.4/gitrepo-add.md, versioned_docs/version-0.4/namespaces.md, versioned_docs/version-0.4/troubleshooting.md, versioned_docs/version-0.6/gitrepo-content.md, versioned_docs/version-0.6/namespaces.md, versioned_docs/version-0.7/gitrepo-add.md, versioned_docs/version-0.7/namespaces.md
Moving local cluster is not supported. This PR deletes the docs in all versions that shows how to do move local cluster.
refers to https://github.com/rancher/fleet/issues/1489
=> Remove instructions to move local clusters

versioned_docs/version-0.7/ref-fleet-yaml.md
several features of 0.8 are present in the 0.7 docs. These features do not work in 0.7 so they should not be in the docs.
=> remove future features from docs

docs/gitrepo-targets.md, versioned_docs/version-0.6/gitrepo-targets.md, versioned_docs/version-0.7/gitrepo-targets.md
Refers to [fleet#1650](https://github.com/rancher/fleet/issues/1650).
This adds a warning for Fleet versions from 0.6 onwards about bundle sizes which may exceed etcd's maximum blob size for bundles containing multiple versions of a chart as a result of target customisations.
Fleet versions prior to 0.6 did not properly support multiple chart versions per bundle, hence that warning is not relevant for them.
=> Document bundle size issue with target-customised chart version

.github/workflows/deploy.yml, .github/workflows/updatecli.yml
Node 16 is out of maintainance now
=> Bump Node version to 20.x in GitHub Action workflow

docs/gitrepo-add.md
While reading the GitRepo documentation at https://fleet.rancher.io/gitrepo-add I found myself confused by some ambiguity in the documentation. I've fixed two issues that I found to be rather important.
1. Alter the language used in the warning regarding known hosts.
The purpose of this change is to bring clarity to what the writer's intent was when using the word "it" to specifically mean a public key. As well I've added a comma to help split the sentence grammatically. Each change independently I found to not be a full solution, but combined make readability a lot easier.
2. Add a header format to the known hosts section and move the warning
I felt that the known hosts section was not immediately recognizable as its own specific section/in addition to, so making it a tertiary header …
=> GitRepo Resource Creation Documentation Clarification

docs/imagescan.md
Adding this to clarify `imagescan` with pre-releases.
Refers to:  https://github.com/rancher/fleet/issues/2096
=> Adds a note for pre-releases as semver ignores them by default

docs/ref-configuration.md, versioned_docs/version-0.6/ref-configuration.md, versioned_docs/version-0.6/ref-fleet-yaml.md, versioned_docs/version-0.7/ref-configuration.md, versioned_docs/version-0.8/ref-configuration.md, versioned_docs/version-0.9/ref-configuration.md
This PR should be merged after https://github.com/rancher/fleet/pull/2240
It replaces all `fleet` repo references from `master` to `main`
Refers to: https://github.com/rancher/fleet/issues/2234
=> Updates fleet repository links after moving to main

docs/gitrepo-add.md, docs/ref-fleet-yaml.md
refers to https://github.com/rancher/fleet/issues/1606
The existing inline documentation is getting too long and hard to read. This adds information on the different types of downloaders.
=> Add sections to fleet yaml reference for helm options

docs/ref-fleet-yaml.md
This moves templating docs to their own section to make it more readable and easier to reference, and adds information about how to escape templating in `fleet.yaml`.
Refers to [fleet#2266](https://github.com/rancher/fleet/issues/2266).
=> Add escaping note to templating docs

docs/installation.md, docs/ref-configuration.md
This commit documents static sharding support in terms of installation and use.
Refers to [fleet#1740](https://github.com/rancher/fleet/issues/1740).
=> Add docs for static sharding

docs/cli/fleet-agent/fleet-agent_clusterstatus.md, docs/cli/fleet-agent/fleet-agent_register.md, docs/cli/fleet-controller/fleet-manager_agentmanagement.md, docs/cli/fleet-controller/fleet-manager_cleanup.md
We should clean up flags in the future. The default root commands set their flags as global.
=> Remove CLI args, which are non-functional

docs/changelogs/changelogs/next.md, docs/changelogs/index.md
Because of this setting https://github.com/rancher/fleet-docs/blob/cf094e78a26d61c1eab5737aa35e60338006a59d/sidebars.js#L84 
The website doesn't build if the changelog directory is empty
=> fix: add generic changelog for next release

update-compose.yaml
Bump to a new docusaurus/releasepost policy that will correctly set links and remove obsolete changelog files
cfr [updatecli/releasepost](https://github.com/updatecli/releasepost/releases/tag/v0.5.0)
=> deps(updatecli): Bump docusaurus/releasepost policy

docs/ref-fleet-yaml.md
* Fixed small typo
* Added sprig documentation link
* Added a basic example to access Labels/Annotations by their keys
=> [DOCS] Fix typo and add documentation link

docs/cli/fleet-cli/fleet.md, docs/cli/fleet-cli/fleet_apply.md
That command does not render bundles into Kubernetes resources, but rather creates bundles from directories, which can be either output or applied on a cluster.
Originates in [fleet#2467](https://github.com/rancher/fleet/pull/2467).
=> Fix `fleet apply` command description

docs/ref-fleet-yaml.md
Refers to: https://github.com/rancher/fleet/issues/2541
=> Adds a note in fleet.yaml's version about OCI vs Semver and the '+' character 

docs/ref-fleet-yaml.md
- Fixed max width
- More or less consistent document style
- Spacing between options
- Generally more line breaks
Especially interesting for reading the fleet.yaml reference, since line breaks are not transformed to fit the width of the screen, but are preserved.
Before and after
Let me know what you think.
=> Visually update fleet.yaml reference page

docs/quickstart.md
Fixing link to the fleet documentation in the Quick Start page, changing from https://rancher.github.io/fleet to https://fleet.rancher.io/
=> Fix broken link in Quick Start page

docs/cli/fleet-controller/fleetcontroller_gitjob.md, docs/installation.md, versioned_docs/version-0.10/cli/fleet-controller/fleetcontroller_gitjob.md, versioned_docs/version-0.10/installation.md
This updates sharding documentation to take node selectors, and the new sharding parameters syntax, into account.
Follow-up to https://github.com/rancher/fleet/pull/2505.
Refers to https://github.com/rancher/fleet/issues/2456.
=> Document node selectors for sharding

docs/enableexperimental.md, docs/oci-storage.md, sidebars.js
Refers to:  https://github.com/rancher/fleet/issues/2670
=> Adds experimental features and OCI storage

docs/cluster-registration.md
I am a newbie in SUSE. I was playing with Fleet and hit this issue: https://github.com/rancher/fleet/issues/68
The doc doesn't indicate expected value for _API_SERVER_URL_ in helm install. There are 2 possible candidates for this value:
1. The URL in values.yaml, generated from the previous step (token generation)
_**apiServerURL**: https://[FQDN]_ such as _https://[rancher-ip].sslip.io_
2. _https://[kubeapi_url]:6443_
While following the steps, the users may take the 1st value, like I did. Developer clarified 2nd value should be used. Hence submitting this PR that specifies which value to be fed, and what not.
Also moved a caution for namespace to the right place, right before the helm install cmd, where this caution is required.
Thanks, Jiwon
=> Elaborate on API_SERVER_URL in agent-initiated cluster reg

docs/cli/fleet-controller/fleetcontroller.md, docs/cli/fleet-controller/fleetcontroller_gitjob.md, versioned_docs/version-0.10/cli/fleet-controller/fleetcontroller.md, versioned_docs/version-0.10/cli/fleet-controller/fleetcontroller_gitjob.md
That flag no longer exists from Fleet 0.10 onwards.
=> Remove mentions to `--disable-gitops` in 0.10+

docs/oci-storage.md
This pull request aims to fix the wrong field for the ociRegistry struct.
In the code the field for the ociRegistry url is named reference.
Depending on the way you want to name this field you could also close this pull request and change the name in the code.
=> fix: changed ociRegistry url field to actual reference field

docs/troubleshooting.md
This provides an overview of where and when to gather clues about what Fleet may be doing wrong, before the section explaining _how_ to do so.
=> Add troubleshooting intro

docs/troubleshooting.md, versioned_docs/version-0.11/troubleshooting.md
This fixes indenting for nested lists to be treated as such, instead of appearing as code blocks.
=> Fix formatting of troubleshooting intro

docusaurus.config.js
Versions 0.10 and 0.11 are still maintained, whereas 0.7 is not.
Refers to https://github.com/rancher/fleet-docs/issues/213.
=> Update end-of-maintenance banners

docs/gitrepo-add.md, versioned_docs/version-0.11/gitrepo-add.md
That paragraph belongs one level higher than it was, not being part of the subsection on private Helm registries.
=> Decrease indentation level for paragraph on credentials in git

docs/gitrepo-add.md
This clarifies that Rancher CA bundles may be used if they are configured, although CA bundles specified in a `GitRepo`'s Helm secret or `cabundle` field will still have precedence over them.
Related to https://github.com/rancher/fleet/pull/3233
=> Document fallback to Rancher CA bundles if configured

docs/quickstart.md
This may help newcomers to gradually find their way towards documentation covering more sophisticated use cases.
Refers to https://github.com/rancher/fleet/issues/2667.
=> Add links to quick start page

docs/cli/fleet-agent/fleet-agent.md, versioned_docs/version-0.10/cli/fleet-agent/fleet-agent.md, versioned_docs/version-0.11/cli/fleet-agent/fleet-agent.md, versioned_docs/version-0.12/cli/fleet-agent/fleet-agent.md
Those links, previously broken, now properly redirect to subcommands.
=> Fix links on `fleet-agent` help page

docs/ref-fleet-yaml.md, versioned_docs/version-0.10/ref-fleet-yaml.md, versioned_docs/version-0.11/ref-fleet-yaml.md, versioned_docs/version-0.12/ref-fleet-yaml.md
This clarifies that, while Helm options support `git::http://`-prefixed chart URLs, using them will not succeed when pointing to a git repository using a custom CA bundle.
It takes the opportunity to somewhat reformat the `fleet.yaml` reference, with collapsible YAML, and further details on the main Helm options being migrated further down the page. This allows better formatting and should hopefully make that page more readable.
Refers to https://github.com/rancher/fleet/issues/3646
=> Document limitation on Helm charts in git with custom CAs

docs/helm-ops.md, docs/ref-status-fields.md
This provides information on statuses and their updates for HelmOp resources.
Resource keys are no longer computed for bundles, and therefore removed.
=> Update status docs

versioned_sidebars/version-0.11-sidebars.json, versioned_sidebars/version-0.9-sidebars.json
Updating missing sidebar entries for v0.11 and v0.9 CLI items: 'fleet gitcloner' and 'fleet cleanup'.
=> Updating Missing Sidebar Entries

docs/helm-ops.md
OCI artifacts are a special use case for HelmOps in terms of version handling.
=> Add note on versions of OCI artifacts for HelmOps

docs/helm-ops.md
The comment specifying that the `chart` field could be omitted when referencing an OCI chart might mislead readers into thinking that non-empty values would still be allowed.
=> Remove empty chart field from OCI HelmOps chart example

docs/cli/fleet-controller/fleet-controller.md, docs/ref-crds.md, docusaurus.config.js, versioned_docs/version-0.10/cli/fleet-agent/fleet-agent_clusterstatus.md, versioned_docs/version-0.10/cli/fleet-agent/fleet-agent_register.md, versioned_docs/version-0.10/ref-crds.md, versioned_docs/version-0.11/cli/fleet-agent/fleet-agent.md, versioned_docs/version-0.11/cli/fleet-agent/fleet-agent_clusterstatus.md, versioned_docs/version-0.11/cli/fleet-agent/fleet-agent_register.md, versioned_docs/version-0.11/ref-crds.md, versioned_docs/version-0.12/cli/fleet-controller/fleet-controller.md, versioned_docs/version-0.12/ref-crds.md, versioned_docs/version-0.13/cli/fleet-controller/fleet-controller.md, versioned_docs/version-0.13/oci-storage.md, versioned_docs/version-0.13/ref-crds.md, versioned_docs/version-0.13/rollout.md, versioned_docs/version-0.6/ref-crds.md, versioned_docs/version-0.7/ref-crds.md, versioned_docs/version-0.8/ref-crds.md, versioned_docs/version-0.9/ref-crds.md
This fixes:
* building issues for 0.13, with images linked with outdated relative paths
* out-of-maintenance banners, which are not yet needed for 0.12 and 0.13
* broken links and anchors across all versions
Our CI, through `yarn build`, would previously only warn about broken links and anchors, which would then be easily missed.
This updates Docusaurus config to throw errors instead, making them fail CI, to enable them to be fixed as early as possible.
=> Fix 0.13 links

docs/gitrepo-content.md, docs/ref-fleet-yaml.md
Overriding a bundle's name can be done through the `name` field in a `fleet.yaml` file.
=> Document bundle naming override
