docusaurus.config.js
=> Adding fleet name to header

docusaurus.config.js
=> Fix incorrect URL for 'Edit this page' button

docs/agent-initiated.md, docs/multi-cluster-install.md, docs/quickstart.md, docs/single-cluster-install.md, src/fleetVersions.js, versioned_docs/version-0.5/agent-initiated.md, versioned_docs/version-0.5/multi-cluster-install.md, versioned_docs/version-0.5/quickstart.md, versioned_docs/version-0.5/single-cluster-install.md
Makes the code blocks more complicated, but we keep URLs in one place only.
=> Add component for versioned URLs

docs/gitrepo-targets.md
Fixes https://github.com/rancher/fleet/issues/728
=> Add note about clusterName target

docs/ref-configuration.md, docs/ref-crd-gitrepo.md, docs/ref-fleet-yaml.md, sidebars.js
This should make it easier to access the existing texts.
=> Add fleet.yaml and GitRepo into reference

docs/gitrepo-structure.md
Related PR: https://github.com/rancher/fleet/pull/671
=> Documentation for values templating

docs/gitrepo-structure.md
Refers to https://github.com/rancher/fleet/pull/725
=> Add documentation for valuesFrom secrets and config maps

docusaurus.config.js
Refers to https://github.com/rancher/fleet/issues/1160
=> Add algolia API

docs/agent-initiated.md, docs/cli/fleet-controller/fleet-manager.md, docs/gitrepo-add.md, docs/namespaces.md, docs/troubleshooting.md, versioned_docs/version-0.4/agent-initiated.md, versioned_docs/version-0.4/namespaces.md, versioned_docs/version-0.5/agent-initiated.md, versioned_docs/version-0.5/namespaces.md
* fixes https://github.com/rancher/fleet-docs/issues/45
* fixes https://github.com/rancher/fleet-docs/issues/47
* closes https://github.com/rancher/fleet-docs/pull/37
=> Update minor docs issues

docs/ref-crds.md, docs/ref-fleet-yaml.md
docs for https://github.com/rancher/fleet/pull/1482
=> Add documention for ignore conditions

docs/ref-crds.md
=> Fix anchor links for array elements in reference

docs/ref-configuration.md
Explain how to configure agent affinity, tolerations and resources.
refers to https://github.com/rancher/fleet/issues/1446
=> Add fleet agent config docs

docs/ref-fleet-yaml.md
refers to https://github.com/rancher/fleet/issues/1552 and https://github.com/rancher/fleet/pull/1580
=> Add overrideTargets and doNotDeploy documentation

docs/ref-gitrepo.md
refers to https://github.com/rancher/fleet/pull/1594
=> Add drift correction docs

docs/ref-fleet-yaml.md
refers to https://github.com/rancher/fleet/issues/1553
=> Add namespaceLabels and namespaceAnnotations documentation

docs/gitrepo-content.md, docs/gitrepo-targets.md, docs/ref-fleet-yaml.md
refers to https://github.com/rancher/fleet/issues/1403
=> Add info about cluster name matcher

docs/ref-crds.md
from https://github.com/rancher/fleet/pull/1639
=> Update API docs

docs/webhook.md
Discussion about an affected use case is available on the internal case SURE-6779.
=> webhook.md: add scalability/performance considerations

docs/namespaces.md, versioned_docs/version-0.4/namespaces.md, versioned_docs/version-0.5/namespaces.md, versioned_docs/version-0.6/namespaces.md, versioned_docs/version-0.7/namespaces.md, versioned_docs/version-0.8/namespaces.md
Namespaces are in use, or used.
=> Fix typo in namespaces docs

docs/ref-fleet-yaml.md
Add `correctDrift` docs to `targetCustomization`
relates to https://github.com/rancher/fleet/issues/1794
=> Add correctDrift docs to targetCustomization

docs/webhook.md
related to https://github.com/rancher/fleet/issues/1998
=> Add azure webhooks doc

docs/gitrepo-content.md, docs/troubleshooting.md
Refers to: https://github.com/rancher/fleet/issues/1631
Note: depends on: https://github.com/rancher/fleet-examples/pull/47
=> Updates the docs to say that nested gitrepos is supported

docs/ref-gitrepo.md
Refers: https://github.com/rancher/fleet/issues/2394
=> Add disablePolling to the docs

docs/installation.md, docs/ref-configuration.md
refers to https://github.com/rancher/fleet/issues/2358
=> Update sharding label in docs

docs/troubleshooting.md
Added troubleshooting documentation related to https://github.com/rancher/fleet/issues/1812
=> Adding documentation to troubleshoot helm error while deploying multiple ressources with same releaseName

docs/gitrepo-add.md, docs/gitrepo-content.md
Closes https://github.com/rancher/fleet/issues/2677
=> Add information about credentials in git

docs/uninstall.md
refers to https://github.com/rancher/fleet-docs/issues/124
=> Give some guidance on Fleet uninstallation

docs/multi-user.md
This PR adds more context about the **workspace isolation** setup with Fleet.
I added few more senteces in order to explain a bit more how to achieve this setup.
This is due to the fact that a recent customer that asked for this.
=> docs: isolated workspaces

docs/ref-gitrepo.md, docs/webhook.md
Related to: https://github.com/rancher/fleet/pull/3490
=> Adds GitRepo webhook secret documentation

docs/cli/fleet-cli/fleet_apply.md, docs/gitrepo-content.md, docs/ref-gitrepo.md
Related to: https://github.com/rancher/fleet/pull/3480 and https://github.com/rancher/fleet/pull/3553
=> Adds user-driven bundle scan docs

docs/bundle-diffs.md
This illustrates how to ignore entire resources, adding an example to the page on bundle diffs.
Refers to https://github.com/rancher/fleet/issues/2051.
=> Add resource ignore example

docs/bundle-add.md, docs/gitrepo-content.md, docs/gitrepo-targets.md, docs/ref-registration.md, docs/troubleshooting.md
A few links contained hard-coded, and outdated, Rancher version numbers.
=> Update versioned links

docs/installation.md
This describes new Helm values introduced by https://github.com/rancher/fleet/pull/3457, their uses and defaults.
=> Document configurable replica counts

docs/cli/fleet-cli/fleet_apply.md, docs/gitrepo-add.md, versioned_docs/version-0.10/cli/fleet-cli/fleet_apply.md, versioned_docs/version-0.10/gitrepo-add.md, versioned_docs/version-0.11/cli/fleet-cli/fleet_apply.md, versioned_docs/version-0.11/gitrepo-add.md, versioned_docs/version-0.12/cli/fleet-cli/fleet_apply.md, versioned_docs/version-0.12/gitrepo-add.md
This provides information about what that feature means and a brief overview of how it works.
=> Document strict host key checks support

.github/workflows/build.yaml
Follow up of #251 without checking for typos
=> ci: add workflow to test website building

docs/observability.md
Related to rancher/fleet#3161 and rancher/fleet#3669
=> Add note about limitations of metrics

docs/gitrepo-add.md
Starting with v0.14, Fleet will support Github Apps as an authentication mechanism for git repositories.
=> Document Github App support for authentication

docs/fine-tune-error.md
=> Fix fine tuning title
